apiVersion: v1
kind: Service
metadata:
  labels:
    app: strimzi
  name: strimzi-kafka-bridge
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: ClientIP
  selector:
    name: strimzi-kafka-bridge