apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-kafka-bridge
  labels:
    app: strimzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-kafka-bridge
    spec:
      containers:
      - name: strimzi-kafka-bridge
        image: strimzi/kafka-bridge:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: AMQP_MODE
          value: SERVER
        - name: AMQP_PORT
          value: "5672"
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 5672
          protocol: TCP
          name: amqp
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          tcpSocket:
            port: amqp